#!/bin/sh

# Simple script to load/store ALSA settings
ALSA_CUSTOM=/media/sdcard/ALSA/asound.state
ALSA_RESET=/media/sdcard/ALSA/delete2reset
ALSACTL_PATH=/media/sdcard/ALSA/alsactl
if mount|grep -q /media/sdcard
then
    if [ ! -d "/media/sdcard/ALSA" ]; then
      mkdir -p "/media/sdcard/ALSA"
    fi
    case "$1" in
      start)
        # save and alsa present - load save
        if [ -f "${ALSA_CUSTOM}" ] && [ -f "${ALSACTL_PATH}" ]; then
          ${ALSACTL_PATH} -f ${ALSA_CUSTOM} restore
        fi
        if [ ! -f "${ALSA_RESET}" ]; then
          echo "" > ${ALSA_RESET}
        fi
        ;;
      stop)
        # alsa and reset files present - save
        if [ -f "${ALSACTL_PATH}" ] && [ -f "${ALSA_RESET}" ]; then
          ${ALSACTL_PATH} -f ${ALSA_CUSTOM} store
        # deletes save
        else
          rm ${ALSA_CUSTOM}
        fi
        ;;
    esac
fi
